import{S as f,i as d}from"./assets/vendor-f33cd494.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const m=document.querySelector(".form-input"),c=document.querySelector(".gallery");let n="";const u=document.querySelector(".loader");m.addEventListener("input",o=>{n=o.target.value.trim()});let p=new f(".gallery a",{overlayOpacity:.8,captionSelector:"img",captionDelay:250,captionPosition:"bottom",captionsData:"alt",className:"simple-lightbox"});const l=document.querySelector(".form");l.addEventListener("submit",o=>{if(o.preventDefault(),n===""){l.reset();return}else{c.innerHTML="";const a=`https://pixabay.com/api/?${new URLSearchParams({key:"43830110-6528f7a21182a7b65b70041af",q:`${n}`,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;u.classList.remove("is-hidden"),g(a).then(t=>{if(t.total===0)d.show({id:null,class:".izi-toast",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"14px",messageLineHeight:"",backgroundColor:"#EF4040",theme:"light",color:"",icon:"",iconText:"",iconColor:"#fff",iconUrl:"./img/Group.svg",maxWidth:450,zindex:null,layout:1,balloon:!1,close:!0,closeOnEscape:!1,closeOnClick:!1,displayMode:0,position:"topRight",target:"",targetFirst:!0,timeout:5e3,rtl:!1,animateInside:!0,drag:!0,pauseOnHover:!0,resetOnHover:!1,progressBar:!0,progressBarColor:"",progressBarEasing:"linear",overlay:!1,overlayClose:!1,overlayColor:"rgba(0, 0, 0, 0.6)",transitionIn:"fadeInUp",transitionOut:"fadeOut",transitionInMobile:"fadeInUp",transitionOutMobile:"fadeOutDown",buttons:{},inputs:{},onOpening:function(){},onOpened:function(){},onClosing:function(){},onClosed:function(){}});else{c.insertAdjacentHTML("afterbegin",h(t));const e=p.refresh();p.on("open.simplelightbox",e)}}).catch(console.error()).finally(()=>u.classList.add("is-hidden"))}n="",l.reset()});function g(o){return fetch(o).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})}function h(o){const s=o.hits,a=[];return s.forEach(t=>{a.push(`<li class="gallery-item">
            <a class="gallery-link" href="${t.largeImageURL}">
            <div class="wrapper">
            <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}">
            <div class="title-wrapper">
            <p class="title">Likes<span>${t.likes}</span></p>
            <p class="title">Views<span>${t.views}</span></p>
            <p class="title">Comments<span>${t.comments}</span></p>
            <p class="title">Downloads<span>${t.downloads}</span></p>
            </div>
            </div>
            </a>
            </li>`)}),a.join("")}
//# sourceMappingURL=commonHelpers.js.map
